<?xml version="1.0" encoding="UTF-8"?>
<definitions name="laydshocbatulop" targetNamespace="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/laydshocbatulop"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/laydshocbatulop" xmlns:ns="http://xml.netbeans.org/schema/mine" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/laydshocbatulop">
            <xsd:import namespace="http://xml.netbeans.org/schema/mine" schemaLocation="../XSD/mine.xsd"/>
        </xsd:schema>
    </types>
    <message name="laydshocbatulopOperationRequest">
        <part name="tenlop" type="xsd:string"/>
    </message>
    <message name="laydshocbatulopOperationResponse">
        <part name="dshocbaCN" type="ns:DanhSachHocBaTheoLop"/>
    </message>
    <message name="laydshocbatulopOperationFault">
        <part name="exception" type="xsd:string"/>
    </message>
    <portType name="laydshocbatulopPortType">
        <operation name="laydshocbatulopOperation">
            <input name="input1" message="tns:laydshocbatulopOperationRequest"/>
            <output name="output1" message="tns:laydshocbatulopOperationResponse"/>
            <fault name="fault1" message="tns:laydshocbatulopOperationFault"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="laydshocbatulop">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="laydshocbatulopPortTypeRole" portType="tns:laydshocbatulopPortType"/>
    </plnk:partnerLinkType>
</definitions>


