<?xml version="1.0" encoding="UTF-8"?>
<definitions name="tracuuhocbacanam" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanlyHocBa/tracuuhocbacanam"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanlyHocBa/tracuuhocbacanam" xmlns:ns="http://xml.netbeans.org/schema/mine" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns0="http://xml.netbeans.org/schema/QLHB_EschoolinkObject">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QuanlyHocBa/tracuuhocbacanam">
            <xsd:import namespace="http://xml.netbeans.org/schema/mine" schemaLocation="../XSD/mine.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/QLHB_EschoolinkObject" schemaLocation="../XSD/Dang_EschoolinkObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="tracuuhocbacanamOperationRequest">
        <part name="id_hocsinh" type="xsd:long"/>
        <part name="namsau" type="xsd:long"/>
        <part name="namtruoc" type="xsd:long"/>
    </message>
    <message name="tracuuhocbacanamOperationResponse">
        <part name="result" type="ns0:HocBa"/>
    </message>
    <portType name="tracuuhocbacanamPortType">
        <operation name="tracuuhocbacanamOperation">
            <input name="input1" message="tns:tracuuhocbacanamOperationRequest"/>
            <output name="output1" message="tns:tracuuhocbacanamOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="tracuuhocbacanam">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="tracuuhocbacanamPortTypeRole" portType="tns:tracuuhocbacanamPortType"/>
    </plnk:partnerLinkType>
</definitions>



