<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SuaGV" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyGiaoVien/SuaGV"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyGiaoVien/SuaGV" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="SuaGVOperationRequest">
        <part name="id_giaovien" type="xsd:long"/>
        <part name="choohientai" type="xsd:string"/>
        <part name="chucvu" type="xsd:string"/>
        <part name="cmnd" type="xsd:string"/>
        <part name="email" type="xsd:string"/>
        <part name="gioitinh" type="xsd:string"/>
        <part name="hinhanh" type="xsd:string"/>
        <part name="ketnapdang" type="xsd:boolean"/>
        <part name="ketnapdoan" type="xsd:boolean"/>
        <part name="ngaycap" type="xsd:date"/>
        <part name="ngaysinh" type="xsd:date"/>
        <part name="ngayvaodang" type="xsd:date"/>
        <part name="ngayvaodoan" type="xsd:date"/>
        <part name="ngayvaotruong" type="xsd:date"/>
        <part name="noicap" type="xsd:string"/>
        <part name="quequan" type="xsd:string"/>
        <part name="sodienthoai" type="xsd:string"/>
        <part name="tengiaovien" type="xsd:string"/>
        <part name="tinhtrangsuckhoe" type="xsd:string"/>
        <part name="tongiao" type="xsd:string"/>
        <part name="trinhdodaotao" type="xsd:string"/>
        <part name="trinhdovanhoa" type="xsd:string"/>
        <part name="id_nguoidung" type="xsd:long" />
        <part name="id_dantoc" type="xsd:long"/>
        <part name="id_tobomon" type="xsd:long"/>





   </message>
    <message name="SuaGVOperationResponse">
        <part name="result" type="xsd:long"/>
    </message>
    <portType name="SuaGVPortType">
        <operation name="SuaGVOperation">
            <input name="input1" message="tns:SuaGVOperationRequest"/>
            <output name="output1" message="tns:SuaGVOperationResponse"/>
       </operation>
    </portType>
    <plnk:partnerLinkType name="SuaGV">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SuaGVPortTypeRole" portType="tns:SuaGVPortType"/>
    </plnk:partnerLinkType>
</definitions>



