<?xml version="1.0" encoding="UTF-8"?>
<definitions name="xoaMonHoc" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/xoaMonHoc"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/xoaMonHoc" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="xoaMonHocOperationRequest">
        <part name="idMonHoc" type="xsd:long"/>
    </message>
    <message name="xoaMonHocOperationResponse">
        <part name="result" type="xsd:boolean"/>
    </message>
    <portType name="xoaMonHocPortType">
        <operation name="xoaMonHocOperation">
            <input name="input1" message="tns:xoaMonHocOperationRequest"/>
            <output name="output1" message="tns:xoaMonHocOperationResponse"/>
        </operation>
    </portType>
    <binding name="xoaMonHocBinding" type="tns:xoaMonHocPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="xoaMonHocOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/xoaMonHoc"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/xoaMonHoc"/>
            </output>
        </operation>
    </binding>
    <service name="xoaMonHocService">
        <port name="xoaMonHocPort" binding="tns:xoaMonHocBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/xoaMonHocService/xoaMonHocPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="xoaMonHoc">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="xoaMonHocPortTypeRole" portType="tns:xoaMonHocPortType"/>
    </plnk:partnerLinkType>
</definitions>

