<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TaoNhom" targetNamespace="http://j2ee.netbeans.org/wsdl/QLThongTinKhoiTao/TaoNhom"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QLThongTinKhoiTao/TaoNhom" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="TaoNhomOperationRequest">
        <part name="tennhom" type="xsd:string"/>
        <part name="mota" type="xsd:string"/>
    </message>
    <message name="TaoNhomOperationResponse">
        <part name="id" type="xsd:long"/>
    </message>
    <portType name="TaoNhomPortType">
        <operation name="TaoNhomOperation">
            <input name="input1" message="tns:TaoNhomOperationRequest"/>
            <output name="output1" message="tns:TaoNhomOperationResponse"/>
        </operation>
    </portType>
    <binding name="TaoNhomBinding" type="tns:TaoNhomPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="TaoNhomOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/QLThongTinKhoiTao/TaoNhom"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/QLThongTinKhoiTao/TaoNhom"/>
            </output>
        </operation>
    </binding>
    <service name="TaoNhomService">
        <port name="TaoNhomPort" binding="tns:TaoNhomBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/TaoNhomService/TaoNhomPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="TaoNhom">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TaoNhomPortTypeRole" portType="tns:TaoNhomPortType"/>
    </plnk:partnerLinkType>
</definitions>

