<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ThemHocSinh" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyHocSinh/ThemHocSinh"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyHocSinh/ThemHocSinh" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns0="http://xml.netbeans.org/schema/EschoolinkObject">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyHocSinh/ThemHocSinh">
            <xsd:import namespace="http://xml.netbeans.org/schema/EschoolinkObject" schemaLocation="../XSD_XML_Object/EschoolinkObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="ThemHocSinhOperationRequest">
        <part name="username" type="xsd:string"/>
        <part name="password" type="xsd:string"/>
        <part name="tenHocSinh" type="xsd:string"/>
        <part name="ngaySinh" type="xsd:date"/>
        <part name="gioiTinh" type="xsd:string"/>
        <part name="diaChiNhaO" type="xsd:string"/>
        <part name="id_thonxom" type="xsd:long"/>
        <part name="id_xaphuongthitran" type="xsd:long"/>
        <part name="id_quanhuyenthanhpho" type="xsd:long"/>
        <part name="id_dantoc" type="xsd:long"/>
        <part name="tonGiao" type="xsd:string"/>
        <part name="hinhAnh" type="xsd:string"/>
        <part name="ketNapDoi" type="xsd:boolean"/>
        <part name="ngayVaoDoi" type="xsd:date"/>
        <part name="ketNapDoan" type="xsd:boolean"/>
        <part name="ngayVaoDoan" type="xsd:date"/>
        <part name="ghiChu" type="xsd:string"/>
        <part name="id_chedouutien" type="xsd:long"/>
        <part name="id_lop" type="xsd:long"/>
        <part name="id_loaihocsinh" type="xsd:long"/>
        <part name="id_khuvuc" type="xsd:long"/>
        <part name="id_quequan" type="xsd:long"/>
        <part name="id_tinh" type="xsd:long"/>
    </message>
    <message name="ThemHocSinhOperationResponse">
        <part name="result" type="xsd:boolean"/>
    </message>
    <portType name="ThemHocSinhPortType">
        <operation name="ThemHocSinhOperation">
            <input name="input1" message="tns:ThemHocSinhOperationRequest"/>
            <output name="output1" message="tns:ThemHocSinhOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="ThemHocSinh">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ThemHocSinhPortTypeRole" portType="tns:ThemHocSinhPortType"/>
    </plnk:partnerLinkType>
</definitions>






