<?xml version="1.0" encoding="UTF-8"?>
<definitions name="LayDanhSachDiemCuaHocSinhByMonHoc" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyDiem/LayDanhSachDiemCuaHocSinhByMonHoc"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyDiem/LayDanhSachDiemCuaHocSinhByMonHoc" xmlns:ns="http://xml.netbeans.org/schema/LoaiDiem" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyDiem/LayDanhSachDiemCuaHocSinhByMonHoc">
            <xsd:import namespace="http://xml.netbeans.org/schema/LoaiDiem" schemaLocation="../XSD_XML_Object/LoaiDiem.xsd"/>
        </xsd:schema>
    </types>
    <message name="LayDanhSachDiemCuaHocSinhByMonHocOperationRequest">
        <part name="id_hocsinh" type="xsd:long"/>
        <part name="id_lop" type="xsd:long"/>
        <part name="id_monhoc" type="xsd:long"/>
        <part name="id_namhoc" type="xsd:long"/>
        <part name="hocky" type="xsd:int"/>
    </message>
    <message name="LayDanhSachDiemCuaHocSinhByMonHocOperationResponse">
        <part name="listdiem" type="ns:ListDiem"/>
    </message>
    <portType name="LayDanhSachDiemCuaHocSinhByMonHocPortType">
        <operation name="LayDanhSachDiemCuaHocSinhByMonHocOperation">
            <input name="input1" message="tns:LayDanhSachDiemCuaHocSinhByMonHocOperationRequest"/>
            <output name="output1" message="tns:LayDanhSachDiemCuaHocSinhByMonHocOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="LayDanhSachDiemCuaHocSinhByMonHoc">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="LayDanhSachDiemCuaHocSinhByMonHocPortTypeRole" portType="tns:LayDanhSachDiemCuaHocSinhByMonHocPortType"/>
    </plnk:partnerLinkType>
</definitions>


