<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="EShoolinkComApp" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/wsdl/QuanLyHocSinh/newWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="EShoolinkComApp" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://j2ee.netbeans.org/wsdl/QuanLyHocSinh/newWSDL" location="http://sanchikaro:18001/EShoolinkComApp-sun-http-binding/QuanLyHocSinh/interface_WSDL/newWSDL.wsdl">
    </import>
  <portType name="dummyCasaPortType">
  </portType>
  <binding name="casaBinding1" type="ns:newWSDLPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="newWSDLOperation">
      <soap:operation/>
      <input name="input1">
        <soap:body use="literal"/>
      </input>
      <output name="output1">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="EShoolinkComAppService1">
    <port name="test" binding="tns:casaBinding1">
      <soap:address location="http://sanchikaro:18001/EShoolinkComAppService1/test"/>
    </port>
  </service>
</definitions>
