<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TimHocSinhTheoLop" targetNamespace="http://j2ee.netbeans.org/wsdl/QLHocSinh/TimHocSinhTheoLop"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QLHocSinh/TimHocSinhTheoLop" xmlns:ns="http://xml.netbeans.org/schema/EschoolinkObject" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns0="http://xml.netbeans.org/schema/ListObject">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QLHocSinh/TimHocSinhTheoLop">
            <xsd:import namespace="http://xml.netbeans.org/schema/EschoolinkObject" schemaLocation="../XSD_XML_Object/EschoolinkObject.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/ListObject" schemaLocation="../XSD_XML_Object/ListObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="TimHocSinhTheoLopOperationRequest">
        <part name="idLop" type="xsd:long"/>
    </message>
    <message name="TimHocSinhTheoLopOperationResponse">
        <part name="part1" type="ns0:ListHocSinh"/>
    </message>
    <portType name="TimHocSinhTheoLopPortType">
        <operation name="TimHocSinhTheoLopOperation">
            <input name="input1" message="tns:TimHocSinhTheoLopOperationRequest"/>
            <output name="output1" message="tns:TimHocSinhTheoLopOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="TimHocSinhTheoLop">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TimHocSinhTheoLopPortTypeRole" portType="tns:TimHocSinhTheoLopPortType"/>
    </plnk:partnerLinkType>
</definitions>





