<?xml version="1.0" encoding="UTF-8"?>
<definitions name="thanhtichhoctap" targetNamespace="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/thanhtichhoctap" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/thanhtichhoctap" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="thanhtichhoctap.xsd"/>
	</xsd:schema>
  </types>
  <message name="outputMsg">
    <part name="part" element="ns:thanhtichhoctap_Response"/>
  </message>
  <message name="inputMsg">
    <part name="part" element="ns:thanhtichhoctap_Request"/>
  </message>
  <portType name="jdbcPortType">
    <operation name="thanhtichhoctap_Operation">
      <input name="input" message="tns:inputMsg"/>
      <output name="output" message="tns:outputMsg"/>
    </operation>
  </portType>
  <binding name="binding" type="tns:jdbcPortType">
    <jdbc:binding xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
    <operation name="thanhtichhoctap_Operation">
    <jdbc:operation xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
      <input name="input">
    <jdbc:input xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" MarkColumnName="" MarkColumnValue="" MoveRowToTableName="" PKName="" PollMilliSeconds="5000" PollingPostProcessing="MoveRow" TableName="thanhtichhoctap" Transaction="NOTransaction" numberOfRecords="" operationType="thanhtichhoctap_Operation" paramOrder="id_sodiem,id_hocsinh" sql="SELECT
  loaidiem.id_loaidiem,
  loaidiem.heso,
  loaidiem.kyhieu,
  loaidiem.tenloaidiem,
  chitietsodiem.id_chitietsodiem,
  chitietsodiem.id_hocsinh,
  chitietsodiem.id_lop,
  chitietsodiem.id_sodiem,
  diem.diem,
  diem.id_diem

FROM
  public.chitietsodiem,
  public.diem,
  public.loaidiem
WHERE
  chitietsodiem.id_chitietsodiem = diem.id_chitietsodiem AND
  diem.id_loaidiem = loaidiem.id_loaidiem AND
(loaidiem.tenloaidiem like 'DTB' OR loaidiem.tenloaidiem like 'DTBCN') AND
  chitietsodiem.id_sodiem=? AND
   chitietsodiem.id_hocsinh=?"/>
      </input>
      <output name="output">
    <jdbc:output xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" returnPartName="part"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="port" binding="tns:binding">
    <jdbc:address xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" jndiName="jdbc/eschoolinkdb"/>
    </port>
  </service>
    <plink:partnerLinkType xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="jdbcpartner">
        <plink:role name="jdbcPortTypeRole" portType="tns:jdbcPortType"/>
    </plink:partnerLinkType>
</definitions>

