<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DB_TimHocSinhTheoKhoiLop_count" targetNamespace="http://j2ee.netbeans.org/wsdl/QLHocSinh/DB_TimHocSinhTheoKhoiLop_count" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://j2ee.netbeans.org/wsdl/QLHocSinh/DB_TimHocSinhTheoKhoiLop_count" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="../../DB_WSDL/find/XSD/DB_TimHocSinhTheoKhoiLop_count.xsd"/>
	</xsd:schema>
  </types>
  <message name="outputMsg">
    <part name="part" element="ns:DB_TimHocSinhTheoKhoiLop_count_Response"/>
  </message>
  <message name="inputMsg">
    <part name="part" element="ns:DB_TimHocSinhTheoKhoiLop_count_Request"/>
  </message>
  <portType name="jdbcPortType">
    <operation name="newuntitled_Operation">
      <input name="input" message="tns:inputMsg"/>
      <output name="output" message="tns:outputMsg"/>
    </operation>
  </portType>
  <binding name="binding" type="tns:jdbcPortType">
    <jdbc:binding xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
    <operation name="newuntitled_Operation">
    <jdbc:operation xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
      <input name="input">
    <jdbc:input xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" MarkColumnName="" MarkColumnValue="" MoveRowToTableName="" PKName="" PollMilliSeconds="5000" PollingPostProcessing="MoveRow" TableName="DB_TimHocSinhTheoKhoiLop_count" Transaction="NOTransaction" numberOfRecords="" operationType="DB_TimHocSinhTheoKhoiLop_count_Operation" paramOrder="id_khoilop,id_namhoc" sql="SELECT
  COUNT(hocsinh.id_hocsinh)
FROM
  public.hocsinh,
  public.tinh,
  public.quanhuyenthanhpho,
  public.dantoc,
  public.loaihocsinh,
  public.nguoidung,
  public.khuvuc,
  public.chedouutien,
  public.lop,
  public.namhoc,
  public.danhsachlop,
  public.khoilop
WHERE
  hocsinh.id_tinh = tinh.id_tinh AND
  hocsinh.id_dantoc = dantoc.id_dantoc AND
  hocsinh.id_loaihocsinh = loaihocsinh.id_loaihocsinh AND
  hocsinh.id_nguoidung = nguoidung.id_nguoidung AND
  hocsinh.id_quanhuyenthanhpho = quanhuyenthanhpho.id_quanhuyenthanhpho AND
  khuvuc.id_khuvuc = hocsinh.id_khuvuc AND
  chedouutien.id_chedouutien = hocsinh.id_chedouutien AND
  lop.id_lop = danhsachlop.id_lop AND
  lop.id_namhoc = namhoc.id_namhoc AND
  lop.id_khoilop = khoilop.id_khoilop AND
  danhsachlop.id_hocsinh = hocsinh.id_hocsinh AND
  hocsinh.bixoahaychua = false AND
  khoilop.id_khoilop = ? AND
  namhoc.id_namhoc = ?"/>
      </input>
      <output name="output">
    <jdbc:output xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" returnPartName="part"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="port" binding="tns:binding">
    <jdbc:address xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" jndiName="jdbc/eschoolinkdb"/>
    </port>
  </service>
    <plink:partnerLinkType xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="jdbcpartner">
        <plink:role name="jdbcPortTypeRole" portType="tns:jdbcPortType"/>
    </plink:partnerLinkType>
</definitions>


