<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TimHocSinhByIdHocSinh" targetNamespace="http://j2ee.netbeans.org/wsdl/QLHocSinh/TimHocSinhByIdHocSinh"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QLHocSinh/TimHocSinhByIdHocSinh" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns0="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:ns1="http://xml.netbeans.org/schema/EschoolinkObject">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QLHocSinh/TimHocSinhByIdHocSinh">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="../DB_WSDL/find/XSD/DB_loadHocSinhByIDHocSinh.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/EschoolinkObject" schemaLocation="../XSD_XML_Object/EschoolinkObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="TimHocSinhByIdHocSinhOperationRequest">
        <part name="idhocsinh" type="xsd:long"/>
    </message>
    <message name="TimHocSinhByIdHocSinhOperationResponse">
        <part name="result" type="ns1:HocSinh"/>
    </message>
    <portType name="TimHocSinhByIdHocSinhPortType">
        <operation name="TimHocSinhByIdHocSinhOperation">
            <input name="input1" message="tns:TimHocSinhByIdHocSinhOperationRequest"/>
            <output name="output1" message="tns:TimHocSinhByIdHocSinhOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="TimHocSinhByIdHocSinh">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TimHocSinhByIdHocSinhPortTypeRole" portType="tns:TimHocSinhByIdHocSinhPortType"/>
    </plnk:partnerLinkType>
</definitions>




