<?xml version="1.0" encoding="UTF-8"?>
<definitions name="tracuuhocbatheohocky" targetNamespace="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/tracuuhocbatheohocky"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/tracuuhocbatheohocky" xmlns:ns="http://xml.netbeans.org/schema/mine" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns0="http://xml.netbeans.org/schema/QLHB_EschoolinkObject">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Quanlyhocsinh/tracuuhocbatheohocky">
            <xsd:import namespace="http://xml.netbeans.org/schema/mine" schemaLocation="../XSD/mine.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/QLHB_EschoolinkObject" schemaLocation="../XSD/Dang_EschoolinkObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="tracuuhocbatheohockyOperationRequest">
        <part name="id_hocsinh" type="xsd:long"/>
        <part name="hocky" type="xsd:integer"/>
        <part name="namsau" type="xsd:integer"/>
        <part name="namtruoc" type="xsd:integer"/>
    </message>
    <message name="tracuuhocbatheohockyOperationResponse">
        <part name="hocbaHK" type="ns0:HocBaTungHK"/>
    </message>
    <portType name="tracuuhocbatheohockyPortType">
        <operation name="tracuuhocbatheohockyOperation">
            <input name="input1" message="tns:tracuuhocbatheohockyOperationRequest"/>
            <output name="output1" message="tns:tracuuhocbatheohockyOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="tracuuhocbatheohocky">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="tracuuhocbatheohockyPortTypeRole" portType="tns:tracuuhocbatheohockyPortType"/>
    </plnk:partnerLinkType>
</definitions>





