<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DB_loadHocSinhByIdHocSinh" targetNamespace="http://j2ee.netbeans.org/wsdl/QLHocSinh/DB_loadHocSinhByIdHocSinh" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://j2ee.netbeans.org/wsdl/QLHocSinh/DB_loadHocSinhByIdHocSinh" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="DB_loadHocSinhByIdHocSinh.xsd"/>
	</xsd:schema>
  </types>
  <message name="outputMsg">
    <part name="part" element="ns:DB_loadHocSinhByIdHocSinh_Response"/>
  </message>
  <message name="inputMsg">
    <part name="part" element="ns:DB_loadHocSinhByIdHocSinh_Request"/>
  </message>
  <portType name="jdbcPortType">
    <operation name="newuntitled_Operation">
      <input name="input" message="tns:inputMsg"/>
      <output name="output" message="tns:outputMsg"/>
    </operation>
  </portType>
  <binding name="binding" type="tns:jdbcPortType">
    <jdbc:binding xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
    <operation name="newuntitled_Operation">
    <jdbc:operation xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
      <input name="input">
    <jdbc:input xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" MarkColumnName="" MarkColumnValue="" MoveRowToTableName="" PKName="" PollMilliSeconds="5000" PollingPostProcessing="MoveRow" TableName="DB_loadHocSinhByIdHocSinh" Transaction="NOTransaction" numberOfRecords="" operationType="DB_loadHocSinhByIdHocSinh_Operation" paramOrder="id_hocsinh" sql="SELECT
  hocsinh.tenhocsinh,
  hocsinh.ten,
  hocsinh.masohocsinh,
  hocsinh.gioitinh,
  hocsinh.ngaysinh,
  hocsinh.hinhanh,
  hocsinh.sonha AS diachi,
  hocsinh.ghichu,
  hocsinh.ketnapdoan,
  hocsinh.ketnapdoi,
  hocsinh.ngayvaodoan,
  hocsinh.ngayvaodoi,
  hocsinh.tongiao,
  hocsinh.id_quequan,
  loaihocsinh.id_loaihocsinh,
  loaihocsinh.tenloaihocsinh,
  loaihocsinh.mota AS motaloaihocsinh,
  nguoidung.ngaytao,
  nguoidung.&quot;password&quot;,
  nguoidung.username,
  khuvuc.id_khuvuc,
  khuvuc.tenkhuvuc,
  khuvuc.mota AS motakhuvuc,
  tinh.id_tinh,
  tinh.tentinh,
  quanhuyenthanhpho.id_quanhuyenthanhpho,
  quanhuyenthanhpho.tenquanhuyenthanhpho,
  xaphuongthitran.id_xaphuongthitran,
  xaphuongthitran.tenxaphuongthitran,
  thonxom.id_thonxom,
  thonxom.tenthonxom,
  chedouutien.id_chedouutien,
  chedouutien.tenchedouutien,
  chedouutien.phantramduocgiam,
  dantoc.id_dantoc,
  dantoc.dantocthieuso,
  dantoc.tendantoc
FROM
  public.hocsinh,
  public.thonxom,
  public.xaphuongthitran,
  public.tinh,
  public.quanhuyenthanhpho,
  public.dantoc,
  public.loaihocsinh,
  public.nguoidung,
  public.khuvuc,
  public.chedouutien
WHERE
  hocsinh.id_tinh = tinh.id_tinh AND
  hocsinh.id_dantoc = dantoc.id_dantoc AND
  hocsinh.id_xaphuongthitran = xaphuongthitran.id_xaphuongthitran AND
  hocsinh.id_loaihocsinh = loaihocsinh.id_loaihocsinh AND
  hocsinh.id_nguoidung = nguoidung.id_nguoidung AND
  hocsinh.id_quanhuyenthanhpho = quanhuyenthanhpho.id_quanhuyenthanhpho AND
  hocsinh.id_thonxom = thonxom.id_thonxom AND
  khuvuc.id_khuvuc = hocsinh.id_khuvuc AND
  chedouutien.id_chedouutien = hocsinh.id_chedouutien AND
  hocsinh.bixoahaychua = false AND
  hocsinh.id_hocsinh = ?"/>
      </input>
      <output name="output">
    <jdbc:output xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" returnPartName="part"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="port" binding="tns:binding">
    <jdbc:address xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" jndiName="jdbc/eschoolinkdb"/>
    </port>
  </service>
    <plink:partnerLinkType xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="jdbcpartner">
        <plink:role name="jdbcPortTypeRole" portType="tns:jdbcPortType"/>
    </plink:partnerLinkType>
</definitions>

