<?xml version="1.0" encoding="UTF-8"?>
<definitions name="LayDanhSachMonHocCuaLop" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyDiem/LayDanhSachMonHocCuaLop"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyDiem/LayDanhSachMonHocCuaLop" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns0="http://xml.netbeans.org/schema/LoaiDiem">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyDiem/LayDanhSachMonHocCuaLop">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="../DB_WSDL/DB_LayDanhSachMonHocCuaLop.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/LoaiDiem" schemaLocation="../XSD_XML_Object/LoaiDiem.xsd"/>
        </xsd:schema>
    </types>
    <message name="LayDanhSachMonHocCuaLopOperationRequest">
        <part name="id_lop" type="xsd:long"/>
    </message>
    <message name="LayDanhSachMonHocCuaLopOperationResponse">
        <part name="listMonHoc" type="ns0:ListMonHoc"/>
    </message>
    <portType name="LayDanhSachMonHocCuaLopPortType">
        <operation name="LayDanhSachMonHocCuaLopOperation">
            <input name="input1" message="tns:LayDanhSachMonHocCuaLopOperationRequest"/>
            <output name="output1" message="tns:LayDanhSachMonHocCuaLopOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="LayDanhSachMonHocCuaLop">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="LayDanhSachMonHocCuaLopPortTypeRole" portType="tns:LayDanhSachMonHocCuaLopPortType"/>
    </plnk:partnerLinkType>
</definitions>




