<?xml version="1.0" encoding="UTF-8"?>
<definitions name="chinhsuahocba" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanlyHocBa/chinhsuahocba"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanlyHocBa/chinhsuahocba" xmlns:ns="http://xml.netbeans.org/schema/QLHB_EschoolinkObject" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QuanlyHocBa/chinhsuahocba">
            <xsd:import namespace="http://xml.netbeans.org/schema/QLHB_EschoolinkObject" schemaLocation="../XSD/Dang_EschoolinkObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="chinhsuahocbaOperationRequest">
        <part name="id_hocba" type="xsd:long"/>
        <part name="diemtrungbinh" type="xsd:double"/>
        <part name="lenlophaykhong" type="xsd:boolean"/>
        <part name="nhanxet" type="xsd:string"/>
        <part name="id_hocluc" type="xsd:long"/>
        <part name="id_namhoc" type="xsd:long"/>
        <part name="id_hanhkiem" type="xsd:long"/>
        <part name="id_lop" type="xsd:long"/>
    </message>
    <message name="chinhsuahocbaOperationResponse">
        <part name="result" type="xsd:boolean"/>
    </message>
    <portType name="chinhsuahocbaPortType">
        <operation name="chinhsuahocbaOperation">
            <input name="input1" message="tns:chinhsuahocbaOperationRequest"/>
            <output name="output1" message="tns:chinhsuahocbaOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="chinhsuahocba">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="chinhsuahocbaPortTypeRole" portType="tns:chinhsuahocbaPortType"/>
    </plnk:partnerLinkType>
</definitions>




