<?xml version="1.0" encoding="UTF-8"?>
<definitions name="tb_GV" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyGiaoVien/tb_GV" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyGiaoVien/tb_GV" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="giaovien.xsd"/>
	</xsd:schema>
  </types>
  <message name="outputMsg">
    <part name="part" element="ns:giaovien"/>
  </message>
  <message name="RetMsg">
    <part name="part" type="xsd:int"/>
  </message>
  <message name="inputMsg">
    <part name="part" element="ns:giaovien"/>
  </message>
  <portType name="jdbcPortType">
    <operation name="find">
      <input name="inputFind" message="tns:inputMsg"/>
      <output name="outputFind" message="tns:outputMsg"/>
    </operation>
  </portType>
  <binding name="binding" type="tns:jdbcPortType">
    <jdbc:binding xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
    <operation name="find">
    <jdbc:operation xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
      <input name="inputFind">
    <jdbc:input xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" MarkColumnName="" MarkColumnValue="" MoveRowToTableName="" PKName="id_giaovien" PollMilliSeconds="5000" PollingPostProcessing="MoveRow" TableName="giaovien" Transaction="NOTransaction" numberOfRecords="" operationType="find" paramOrder="id_giaovien" sql="SELECT id_giaovien, choohientai, chucvu, cmnd, email, gioitinh, hinhanh,
       ketnapdang, ketnapdoan, ngaycap, ngaysinh, ngayvaodang, ngayvaodoan,
       ngayvaotruong, noicap, quequan, sodienthoai, tengiaovien, tinhtrangsuckhoe,
       tongiao, trinhdodaotao, trinhdovanhoa, id_nguoidung, id_dantoc,
       id_tobomon
  FROM giaovien where id_giaovien=?"/>
      </input>
      <output name="outputFind">
    <jdbc:output xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" returnPartName="part"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="port" binding="tns:binding">
    <jdbc:address xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" jndiName="jdbc/eschoolinkdb"/>
    </port>
  </service>
    <plink:partnerLinkType xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="jdbcpartner">
        <plink:role name="jdbcPortTypeRole" portType="tns:jdbcPortType"/>
    </plink:partnerLinkType>
</definitions>

