<?xml version="1.0" encoding="UTF-8"?>
<definitions name="suaSoDiemDanh" targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/suaSoDiemDanh"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/suaSoDiemDanh" xmlns:ns="http://xml.netbeans.org/schema/EschoolinkObject" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/suaSoDiemDanh">
            <xsd:import namespace="http://xml.netbeans.org/schema/EschoolinkObject" schemaLocation="../../XSD_XML_Object/EschoolinkObject.xsd"/>
        </xsd:schema>
    </types>
    <message name="suaSoDiemDanhOperationRequest">
        <part name="soDiemDanh" type="ns:SoDiemDanh"/>
    </message>
    <message name="suaSoDiemDanhOperationResponse">
        <part name="result" type="xsd:boolean"/>
    </message>
    <portType name="suaSoDiemDanhPortType">
        <operation name="suaSoDiemDanhOperation">
            <input name="input1" message="tns:suaSoDiemDanhOperationRequest"/>
            <output name="output1" message="tns:suaSoDiemDanhOperationResponse"/>
        </operation>
    </portType>
    <binding name="suaSoDiemDanhBinding" type="tns:suaSoDiemDanhPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="suaSoDiemDanhOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/suaSoDiemDanh"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/QuanLyChuyenMon/suaSoDiemDanh"/>
            </output>
        </operation>
    </binding>
    <service name="suaSoDiemDanhService">
        <port name="suaSoDiemDanhPort" binding="tns:suaSoDiemDanhBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/suaSoDiemDanhService/suaSoDiemDanhPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="suaSoDiemDanh">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="suaSoDiemDanhPortTypeRole" portType="tns:suaSoDiemDanhPortType"/>
    </plnk:partnerLinkType>
</definitions>

